// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmgxfgknvyvqevkrrlsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZ3hmZ2tudnl2cWV2a3JybHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjY3MzUsImV4cCI6MjA2OTcwMjczNX0.fKKrJ8zYcFCCAku5CEydsCyxJNaERl1MBLhmeGH3B90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});